name: Deploy Code to VPS

on:
  push:
    branches:
      - master

jobs:
  upload_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Deploy Code to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          TARGET_PATH: /home/arsen/projects/sinatra_blog_app
          SERVICE_NAME: sinatra-blog

        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          # Now copy the files
          scp -i private_key -P $SSH_PORT -o StrictHostKeyChecking=no -r . $VPS_USER@$VPS_HOST:$TARGET_PATH

          # Restart the service
          ssh -i private_key -p $SSH_PORT -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << EOF
            sudo supervisorctl restart $SERVICE_NAME
            echo "Deployment successful! Service restarted."
          EOF
